### ISSUE TITLE
rrd.create is not a function

### ISSUE THREAD

**Issue by JeromeVi** [Orion98MC/node_rrd#17]
Hi, first of all thank you for your nodeJS rrd ! But I'm not sure that I have installed it correctly so there are all my steps:

```
brew install rrdtool  
meteor npm install rrd  
meteor npm install rrdtool
meteor npm install node-rrdtool
meteor npm install -g node-gyp
```

Then I have followed your basic usage and example and I created the rrd object :
`var rrd = require("rrd");
`
And when the errors hapenned I tried to display rrd to see if it was something and the result is:

` { RRD: { [Function: RRD] restore: [Function] } }
`

So maybe I have installed rrd with a wrong way ? Or you have an idea ?

**Comment by Orion98MC** [comment]
Hi Jerome,

The install process is described in the main page of the project. It seems you did not follow it. 

The most important to note is that AFAIK there is no npm package of this project. You need to install and compile it as explained in the README file. 

The package you are requiring in your js code is an other package not this one, and you end up with very different results.

**Comment by JeromeVi** [comment]
And why there is not npm package ? So ok I'll uninstall all and try to make it as you describe it

**Comment by Orion98MC** [comment]
I didn't do it. But anyone can ;)

**Comment by JeromeVi** [comment]
https://www.youtube.com/watch?v=ZXsQAXx_ao0 ;-) 

So I'll try to make it works without the npm package
